version: 0.1

phases:
  install:
    commands:
      - echo Installing .NET Core runtime...
      - sudo apt-get update
      - sudo apt-get install -y dotnet-sdk-8.0

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 494052612135.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building container image and pushing to ecr through dotnet publish command...
      - dotnet publish --os linux --arch x64 /t:PublishContainer

artifacts:
  files:
    - '**/*'
  discard-paths: yes
