version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing .NET Core runtime...
      - sudo apt-get update -y
      - sudo apt-get install -y apt-transport-https
      - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get update -y
      - sudo apt-get install -y dotnet-sdk-8.0

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 339712877508.dkr.ecr.us-west-1.amazonaws.com
      - ls
      - LATEST_TAG=$(git tag -l --sort=-v:refname | head -n 1)
      - echo Latest tag is $LATEST_TAG

  build:
    commands:
      - echo Building container image and pushing to ecr through dotnet publish command...
      - dotnet publish --os linux --arch x64 /t:PublishContainer

artifacts:
  files:
    - '**/*'
  discard-paths: yes



# publish command details - is it building the application or not
# image tag based on git tag 